version: '3.4'

networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.10/24
          gateway: 192.168.1.254

services:
  client-configuration:
    image: docker.io/dev1775/client-configuration:latest
    depends_on:
      - "mssql"
    container_name: clientconfiguration-services
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - sql_connection_string=Server=192.168.1.240,1433;Database=ClientConfigurationDB;TrustServerCertificate=True;User Id=sa;password=SqlLocal123!;
      - ASPNETCORE_URLS=http://+:5000
    networks:
      dev:
        ipv4_address: 192.168.1.230
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SqlLocal123!
    ports:
      - 1433:1433
    restart: always
    volumes:
      - C:/DockerVolumes/SqlData/data:/var/opt/mssql/data
      - C:/DockerVolumes/SqlData/log:/var/opt/mssql/log
      - C:/DockerVolumes/SqlData/secrets:/var/opt/mssql/secrets
    networks:
      dev:
        ipv4_address: 192.168.1.240